src/posts/urls.py
from django.conf.urls import url
from .views import (
			post_create,
			post_detail,
			post_list,
			post_update,
			post_delete,
			entry_index,
	)

urlpatterns = [
   
    url(r'^create/$', post_create,),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail"),
    url(r'^list/$', post_list, name="list"),
    url(r'^(?P<id>\d+)/edit/$', post_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', post_delete),
    url(r'^entry/$',entry_index)
]

src/trydjango19/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from account.views import (
    login_view,
    logout_view,
    register_view,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^register/', register_view, name="register_view"),
    url(r'^login/', login_view, name="login_view"),
    url(r'^logout/', logout_view, name="logout_view")
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from  comment.models import Comment
from django.contrib.contenttypes.models import ContentType


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # posts.objects.all() = return (PostManager, self).all() overiding the all() function
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


# Create your models here.
class Posts(models.Model):
    title = models.CharField(max_length=200)
    # slug = models.SlugField(unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    image = models.FileField(null=True, blank=True, upload_to=upload_location)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    create_date = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id})  # reverse is going to pass the id to url of named detail

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    class Meta:
        ordering = ['-create_date', ]


# def create_slug(instance, new_slug=None):
# 	slug = slugify(instance.title)
# 	if new_slug is not None:
# 		slug = new_slug
# 	qs = Posts.objects.filter(slug=slug).order_by("-id")
# 	exists = qs.exists()
# 	if exists:
# 		new_slug = "%s-%s" %(slug, qs.first().id)
# 		return create_slug(instance, new_slug=new_slug)
# 	return slug

# def pre_save_post_receiver(sender, instance, *args, **kwargs):
# 	if not instance.slug:
# 		instance.id = create_slug(instance)


# pre_save.connect(pre_save_post_receiver, sender=Posts)

class Demo(models.Model):
    title = models.CharField(max_length=200)
    # slug = models.SlugField(unique=True)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    # image = models.FileField(null=True, blank=True, upload_to=upload_location)
    content = models.TextField()

    # draft = models.BooleanField(default=False)
    # publish = models.DateField(auto_now=False,auto_now_add=False)
    # updated = models.DateTimeField(auto_now=True,auto_now_add=False)
    # create_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __unicode__(self):
        return self.title

src/posts/forms.py
from django import forms
from .models import Posts
from pagedown.widgets import PagedownWidget


class PostForms(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Posts
        fields = [
            'title',
            'content',
            'image',
            'publish',
            'draft',
        ]

src/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from posts.models import Posts, Demo
from .forms import PostForms
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

try:
    from urllib import quote_plus
except:
    pass
from django.utils import timezone
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.contenttypes.models import ContentType
from comment.models import Comment
from comment.form import CommentForm
from django.contrib.contenttypes.models import ContentType


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForms(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)  # which means that the object is
        # created but it's not actually saved to the db which is useful if you want to change some data before actually saving it
        # print form.cleaned_data.get('title')
        instance.save()
        print "Hi inside if_statement"
        messages.success(request, 'Posts Created Successfully')
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        print "inside else"
    # messages.error(request, 'Not Created')
    context = {
        "form": form,
    }

    return render(request, 'post_form.html', context)


def post_detail(request, id=None):
    instance = get_object_or_404(Posts, id=id)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    initial_data = {
        "content_type": instance.get_content_type,  # look inside Post model function
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)  # this is comming from model
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get("content")
        print content_data

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    # comments = Comment.objects.filter_by_instance(instance)
    comments = instance.comments
    context = {
        'obj_detail': instance,
        'title': instance.title,
        'share_string': share_string,
        'comments': comments,
        'form': form,
    }

    return render(request, 'detail.html', context)


def post_list(request):
    today = timezone.now().date()
    queryset_list = Posts.objects.active()  # Posts.objects.filter(publish__lte=timezone.now)
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Posts.objects.all()
    query = request.GET.get('query')  # search code starts from here
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query) |
            Q(content__icontains=query)
        ).distinct()

    paginator = Paginator(queryset_list, 5)  # Show 5 contacts per page
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    # if request.user.is_authenticated():
    # 	context = {
    # 				'list': 'my logged in user'
    # 	}
    # 	return render(request, 'index.html', context)
    # else:
    # 	context = {
    # 				'list' : 'list'
    # 	}
    context = {
        'obj_list': queryset,
        'today': today,
    }

    return render(request, 'list.html', context)


def post_update(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Posts, id=id)
    form = PostForms(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)  # whatever the form data is we need to show in front end
        # so,we've saved into some instance & pass it as a context to template.
        instance.save()
        messages.success(request, 'Posts Edited Successfully')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'form': form,
        'instance': instance,
    }

    return render(request, 'post_form.html', context)


def post_delete(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Posts, id=id)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")


def entry_index(request, template='entry_index.html', page_template='entry_index_page.html'):
    context = {
        'entries': Demo.objects.all(),
        'page_template': page_template,
    }
    if request.is_ajax():
        template = page_template
    return render_to_response(
        template, context, context_instance=RequestContext(request))

src/templates/base.html
{% load staticfiles %}
<html>
<head>
	<title>
		{% block title %}try django 1.9{% endblock title %}
	</title>

	<link rel="stylesheet" href="{% static 'css/base.css' %}" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<style>
		{% block style %}{% endblock style %}
	</style>
	{% block head_extra %}{% endblock head_extra %}
</head>
	<body>
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	{% include "message_display.html" %}
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'posts:list'  %}">Home</a></li>
            <li><a href="{% url 'posts:list' %}">Post</a> </li>
            {%  if not request.user.is_authenticate %}
                <li class="pull-right"><a href="{% url 'login_view' %}">Login</a></li>
                <li class="pull-right"><a href="{% url 'register_view' %}">Register</a></li>
            {% else %}
                <li class="pull-right"><a href="{% url 'logout_view' %}">Logout</a></li>
            {% endif  %}

        </ol>
		{% block content %}
		{% endblock content %}
	</div>
	<!-- Latest compiled and minified JavaScript -->

{% block js %}
<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
$(document).ready(function(){
    // facebook plugin code
    $(".content-markdown").each(function(){
            	var content = $(this).text()  //converts the DOM element returned  this to a jQuery object, from which, you can continue using jQuery on
            var markedContent = marked(content)
            $(this).html(markedContent)
    })

    $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive")
    })
    //fb plugin code ends here
// Form preview code 
    var titleInput = $('#id_title')
   // $("#preview-title").text(titleItem.val())
   function setTitle(value){
   //	var title = value
   	$('#preview-title').text(value)
   }

   setTitle(titleInput.val())

   titleInput.keyup(function(){
   		var newTitle = $(this).val()
   		setTitle(newTitle)
   })



    var contentInput = $('#id_content')
    //$("#preview-content").html(marked(contentItem.val()))
    function setContent(value){
    	var markedContent = marked(value)
    	$('#preview-content').html(markedContent)
    	$('#preview-content img').each(function(){
    			$(this).addClass('img-responsive')
    	})
    }
    setContent(contentInput.val())

    contentInput.keyup(function(){
    	var newContent = $(this).val()
    	setContent(newContent)
    })
// form preview code ends here
})
</script>
{% endblock %}


</body>
</html>

src/templates/detail.html
{% extends "base.html" %}
{% load urlify %}

<h1>{% block title %} {{title}} | {{block.super}}</h1>
{% endblock title %}

{% block content %}
		<div class='col-sm-6 col-sm-offset-3'>
			{% if obj_detail.image %}
			<img src="{{ obj_detail.image.url }}" class="img-responsive" />
			{% endif %}
			<h1> {{obj_detail.title}} <small> {% if obj_detail.draft %} <span style="color: red">Draft</span>{% endif %} {{obj_detail.publish}} </small> </h1> <br/>
			<p><div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>



			<!-- <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"> Facebook </a>

			<a href="https://twitter.com/home?status={{obj_detail.content|truncatechars:80|urlify}}%20{{request.build_absolute_uri}}"> Twitter </a>

			<a href='https://plus.google.com/share?url=http://codingforentrepreneurs.com'>Google</a>

			<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{obj_detail.title}}&summary={{share_string}}&source={{request.build_absolute_uri}}"> Linkedin </a> -->

			{% if obj_detail.user.get_full_name %} <p>AUTHOR : {{obj_detail.user.get_full_name}}</p> {% endif %}

			<div class="content-markdown">{{obj_detail.content }}<br/></div>
                <p class="lead">Comments</p>
                <form method="POST" action="."> {% csrf_token %}
            {{ form }}
            <input type='submit' value='Post comment' class='btn btn-default'>
        </form>
            <div>
                {% for comment in comments %}
                    <div class="">
                        {{ comment.content }}
                        <br/>
                        via {{ comment.user }} | {{ comment.timestamp | timesince }} ago
                        <hr />
                    </div>
                {% endfor %}
            </div>
{#			<div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>#}
{% endblock content %}

src/templates/entry_index.html
<h2>Entries:</h2>
{% include page_template %}

src/templates/entry_index_page.html
{% for e in entries %}
	
		{{e.title}}<br />
		{{e.content}} <br />    
{% endfor %}

src/templates/list.html
{% extends "base.html" %}

{% block title %} {{obj_list.title}} | {{block.super}}  {% endblock title %}

{% block content %}
<div class="col-sm-6 col-sm-offset-2">
  <h2>	List </h2>
  <form method="GET" action="">
    <input type="text" placeholder="Search Post" name="query" value="{{request.GET.query}}" />
    <input type="Submit" value="Submit" />
  </form>
  
	{% for obj in obj_list %}
	<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
    {% if obj.image %}
    <img src ='{{ obj.image.url }}' class="img-responsive"/>
    {% endif %}
     <!--  <img src="..." alt="..."> -->
      <div class="caption post-detail-item">
      {% if obj.draft %} <h3> Draft </h3> {% endif %} {% if obj.publish > today %} <h3> Future Post </h3> {% endif %}

        <h3><a href="{% url "posts:detail" obj.id %}">{{obj.title}}</a><small> {{obj.create_date|timesince}} ago </small> </h3><br/>
        {% if obj.user.get_full_name %} <p>{{ obj.user.get_full_name|safe }}</p> {% endif %}
          {{obj.get_markdown|safe}}<br/>
        <p><a href="{% url "posts:detail" obj.id %}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<!--   {% cycle "" "</div class='col-sm-12'><hr /></div><div class='row'>"%}
 --> 
 </div> 
 <hr />
 {% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if obj_list.has_previous %}
            <a href="?page={{ obj_list.previous_page_number }}{% if request.GET.query %}&query={{request.GET.query}} {% endif %}">previous</a>
        {% endif %}

        <span class="current"> 
             Page {{ obj_list.number }} of {{ obj_list.paginator.num_pages }}.
        </span>

        {% if obj_list.has_next %}
            <a href="?page={{ obj_list.next_page_number }}{% if request.GET.query %}&query={{request.GET.query}}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}

src/templates/login_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
		<h1> {{ title }} </h1>
        <hr />
		<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
			{{form}}<br />
			<input type="Submit" class= "btn btn-primary" value={{ title }}>
		</form>
</div>
{% endblock %}

src/templates/message_display.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

src/templates/post_form.html
{% extends "base.html" %}
{% load social_widgets %}
{% block head_extra %}
	{{form.media}}
{% endblock head_extra %}

{% block content %}
<div class="col-sm-6">
	<h1>Preview</h1>
	<div class="content-preview">
		<h3 id="preview-title"> </h3>
		<p id="preview-content"></p> 
	</div>
</div>

<div class="col-sm-5">
		<h1> Form </h1>
		<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
			{{form.as_p}}
			<input type="Submit" class= "btn btn-primary" value="Create Post">
		</form>
</div>

	<div class="col-sm-12">
		<div class="col-sm-4 "> 
			<h1> Facebook widget </h1> 
			{% social_widget_render "facebook/likebox.html" locale="en_US" app_id=12345678 href="https://www.facebook.com/NASSCOMOfficial" height=300 colorscheme="light" force_wall=False header=True show_border=True show_faces=False stream=True width=250 %}
		</div> 
		<div class="col-sm-4"> 
			<h1> Twiter widget </h1> 
			{% social_widget_render "twitter/follow_button.html" username="BillGates" show_screen_name=True show_count=False size="medium" dnt=False %}

			{% social_widget_render "twitter/share_button.html" href="http://www.twitter.com" username="BillGates"  %}
		</div>
		<div class="col-sm-4">
			<h1> Google Plus widget </h1>
			{% social_widget_render "google/plus_person_badge.html" language="en-US" href="https://plus.google.com/+SergeyBrin" layout="portrait" showcoverphoto=True showtagline=True theme="light" width=300 %}
		</div>
 
	</div> 

{% endblock content %}
	  